version: 1.0.0.{build}

image: Visual Studio 2017

branches:
  only:
    - master

configuration: Release

build:
  project: ProPublicaCongressAPI.sln
  publish_nuget: true
  include_nuget_references: true
  
cache:
  - packages -> **\packages.config
  
before_build:
  - cmd: nuget restore

after_build:
- ps: >-
    $xmlPath = "$env:appveyor_build_folder\ProPublicaCongressAPI\ProPublicaCongressAPI.csproj"

    $xml = [xml](get-content $xmlPath)

    $propertyGroup = $xml.Project.PropertyGroup | Where { $_.PackageVersion}

    $propertyGroup.PackageVersion = $env:appveyor_build_version

    $xml.Save($xmlPath)

    msbuild %appveyor_build_folder%\ProPublicaCongressAPI\ProPublicaCongressAPI.csproj /t:pack

deploy:
  provider: NuGet
  api_key:
    secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
  skip_symbols: false
  artifact: /.*\.nupkg/