version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
build_script:
- ps: >-
    nuget restore

    $xmlPath = "$env:appveyor_build_folder\ProPublicaCongressAPI\ProPublicaCongressAPI.csproj"

    $xml = [xml](get-content $xmlPath)

    $propertyGroup = $xml.Project.PropertyGroup | Where { $_.PackageVersion}

    $propertyGroup.PackageVersion = $env:appveyor_build_version

    $xml.Save($xmlPath)

    msbuild $xmlPath /t:pack /p:Configuration=Release
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
  skip_symbols: true